"""Verification badges.

The one distribution mechanism proven to work in this ecosystem, measured
rather than assumed: punkpeye/awesome-mcp-servers carries 2,107 Glama score
badges across 3,483 entries, 60.5% of the whole list, while Smithery is
mentioned twice and PulseMCP zero. Glama did not win by having pages, its
directory ranks for nothing; it won because maintainers paste its badge into
their own READMEs. Every embed is a durable backlink from a repository we do
not control, and it is pull rather than push: people add it because it makes
their server look credible.

Ours says something Glama's cannot: not an opaque score but evidence. We
handshook with the endpoint and read its tool list back. The badge states the
count and whether the endpoint answers, and nothing else.

Never trust language. "verified" here means reachability and capability were
observed; the badge must never read as an endorsement, a safety rating or a
certification, which is also why there is no colour-graded score. Two states:
it answers, or we could not reach it.

SVG is generated by hand rather than through a library because the shape is
shields.io flat style, fixed and tiny, and a dependency for 40 lines of
template would be the heavier risk.
"""
from __future__ import annotations

import sqlite3
import time

from . import config

_CACHE: dict[str, tuple[float, tuple]] = {}
_TTL = 3600

# Approximate glyph advance for Verdana 11px, the shields.io convention. Close
# enough for badge layout; text is also centred so small errors split evenly.
_W = 6.9


def _text_w(s: str) -> int:
    return int(len(s) * _W) + 10


def stats_for(conn: sqlite3.Connection, publisher: str) -> tuple | None:
    """(tools, servers, responding_servers) for one publisher, cached.

    Badges get embedded in READMEs and fetched by every visitor to that repo,
    so this must never run four aggregate queries per view.
    """
    key = publisher.lower().strip()
    now = time.time()
    got = _CACHE.get(key)
    if got and now - got[0] < _TTL:
        return got[1]
    row = conn.execute(
        """SELECT
             (SELECT COUNT(*) FROM tools t JOIN entries e2 ON e2.key=t.entry_key
               WHERE lower(e2.publisher)=?) AS tools,
             COUNT(*) AS servers,
             SUM(CASE WHEN mcp_status LIKE 'ok%' OR mcp_status='auth'
                      THEN 1 ELSE 0 END) AS responding
           FROM entries
           WHERE lower(publisher)=? AND type_family='mcp-server'""",
        (key, key)).fetchone()
    if not row or not row["servers"]:
        _CACHE[key] = (now, None)
        return None
    out = (row["tools"] or 0, row["servers"] or 0, row["responding"] or 0)
    _CACHE[key] = (now, out)
    return out


def _svg(label: str, value: str, value_color: str) -> str:
    lw, vw = _text_w(label), _text_w(value)
    w = lw + vw
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="20" role="img" aria-label="{label}: {value}">
<title>{label}: {value}</title>
<linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient>
<clipPath id="r"><rect width="{w}" height="20" rx="3" fill="#fff"/></clipPath>
<g clip-path="url(#r)">
<rect width="{lw}" height="20" fill="#1b1b1e"/>
<rect x="{lw}" width="{vw}" height="20" fill="{value_color}"/>
<rect width="{w}" height="20" fill="url(#s)"/>
</g>
<g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">
<text x="{lw/2:.0f}" y="14" fill="#010101" fill-opacity=".3">{label}</text>
<text x="{lw/2:.0f}" y="13">{label}</text>
<text x="{lw + vw/2:.0f}" y="14" fill="#010101" fill-opacity=".3">{value}</text>
<text x="{lw + vw/2:.0f}" y="13">{value}</text>
</g></svg>"""


def render(conn: sqlite3.Connection, publisher: str) -> str:
    """The badge for one publisher.

    A publisher we do not hold gets a neutral "not indexed" badge rather than
    an error: the URL will be pasted into READMEs before we have crawled the
    domain, and a broken image where a badge should be reads as our failure,
    not theirs.
    """
    st = stats_for(conn, publisher)
    if st is None:
        return _svg("neuronto", "not indexed yet", "#6c6c74")
    tools, servers, responding = st
    if tools > 0:
        label = f"{tools:,} verified tool" + ("s" if tools != 1 else "")
        if responding:
            return _svg("neuronto", label + " · responding", "#2f6f4f")
        return _svg("neuronto", label, "#3a5f8a")
    if responding:
        return _svg("neuronto", "responding · auth required", "#3a5f8a")
    return _svg("neuronto", "indexed", "#6c6c74")


def snippet(publisher: str) -> str:
    """The paste-ready markdown a maintainer embeds."""
    B = config.PUBLIC_BASE
    return (f"[![Neuronto verified tools]({B}/badge/{publisher}.svg)]"
            f"({B}/console?domain={publisher})")
