"""Verification badges.

The one distribution mechanism proven to work in this ecosystem, measured
rather than assumed: punkpeye/awesome-mcp-servers carries 2,107 Glama score
badges across 3,483 entries, 60.5% of the whole list, while Smithery is
mentioned twice and PulseMCP zero. Glama did not win by having pages, its
directory ranks for nothing; it won because maintainers paste its badge into
their own READMEs. Every embed is a durable backlink from a repository we do
not control, and it is pull rather than push: people add it because it makes
their server look credible.

Ours says something Glama's cannot: not an opaque score but evidence. We
handshook with the endpoint and read its tool list back. The badge states the
count and whether the endpoint answers, and nothing else.

Never trust language. "verified" here means reachability and capability were
observed; the badge must never read as an endorsement, a safety rating or a
certification, which is also why there is no colour-graded score. Two states:
it answers, or we could not reach it.

SVG is generated by hand rather than through a library because the shape is
shields.io flat style, fixed and tiny, and a dependency for 40 lines of
template would be the heavier risk.
"""
from __future__ import annotations

import sqlite3
import time

from . import config

_CACHE: dict[str, tuple[float, tuple]] = {}
_TTL = 3600

# Approximate glyph advance for Verdana 11px, the shields.io convention. Close
# enough for badge layout; text is also centred so small errors split evenly.
_W = 6.9


def _text_w(s: str) -> int:
    return int(len(s) * _W) + 10


def stats_for(conn: sqlite3.Connection, publisher: str) -> tuple | None:
    """(tools, servers, responding_servers) for one publisher, cached.

    Badges get embedded in READMEs and fetched by every visitor to that repo,
    so this must never run four aggregate queries per view.
    """
    key = publisher.lower().strip()
    now = time.time()
    got = _CACHE.get(key)
    if got and now - got[0] < _TTL:
        return got[1]
    row = conn.execute(
        """SELECT
             (SELECT COUNT(*) FROM tools t JOIN entries e2 ON e2.key=t.entry_key
               WHERE lower(e2.publisher)=?) AS tools,
             COUNT(*) AS servers,
             SUM(CASE WHEN mcp_status LIKE 'ok%' OR mcp_status='auth'
                      THEN 1 ELSE 0 END) AS responding
           FROM entries
           WHERE lower(publisher)=? AND type_family='mcp-server'""",
        (key, key)).fetchone()
    if not row or not row["servers"]:
        _CACHE[key] = (now, None)
        return None
    out = (row["tools"] or 0, row["servers"] or 0, row["responding"] or 0)
    _CACHE[key] = (now, out)
    return out


# Per-character advance for the 11px UI stack below, measured against the
# common fallbacks. Digits and capitals are wider; a table beats one average.
_ADV = {**{c: 6.3 for c in "abcdeghknopqsuvxyz"}, **{c: 3.0 for c in "iljt.,:'|!"},
        **{c: 4.6 for c in "fr "}, **{c: 6.9 for c in "mw"},
        **{c: 7.2 for c in "ABCDEFGHKLNOPQRSTUVXYZ0123456789"},
        **{c: 8.6 for c in "MW"}, **{c: 3.6 for c in "-"}}


def _text_w(s: str) -> float:
    return sum(_ADV.get(c, 6.4) for c in s)


# Monochrome by design. A colour-graded badge invites the reader to treat it as
# a score, and this is not a score: it is a statement that we fetched something
# and it answered. Black on white, white on black, and a variant that follows
# the reader's own setting, because a badge that fights the page it sits in is
# the thing maintainers quietly delete.
_THEMES = {
    "light": ("#FFFFFF", "#0A0A0B", "#D6D6DA", "#6C6C74"),
    "dark":  ("#0A0A0B", "#FAFAFA", "#2A2A2E", "#8A8A93"),
}
_FONT = ("ui-sans-serif,-apple-system,BlinkMacSystemFont,'Segoe UI',Inter,"
         "Helvetica,Arial,sans-serif")

# The mark: three ascending bars, the same glyph as the site favicon, drawn as
# paths so no font or external file is needed.
_MARK = ('<rect x="0" y="5.5" width="2.4" height="5" rx="1.2" fill="{fg}"/>'
         '<rect x="4" y="2.5" width="2.4" height="8" rx="1.2" fill="{fg}"/>'
         '<rect x="8" y="0" width="2.4" height="10.5" rx="1.2" fill="{fg}"/>')


def _svg(label: str, value: str, theme: str = "auto") -> str:
    """A flat, monochrome badge. `theme` is light, dark or auto."""
    pad, gap, mark_w = 9.0, 7.0, 10.4
    lw = mark_w + 5.0 + _text_w(label)
    left_w = pad + lw + gap
    right_w = _text_w(value) + pad + gap
    w = round(left_w + right_w, 1)
    h = 20.0
    lx = pad + mark_w + 5.0
    vx = left_w + (right_w - gap) / 2 - pad / 2 + gap / 2
    aria = f"{label}: {value}"

    if theme in _THEMES:
        bg, fg, border, mut = _THEMES[theme]
        style = (f"<style>.bg{{fill:{bg}}}.fg{{fill:{fg}}}.bd{{stroke:{border}}}"
                 f".mut{{fill:{mut}}}</style>")
    else:
        lb, lf, lbd, lm = _THEMES["light"]
        db, df, dbd, dm = _THEMES["dark"]
        style = (f"<style>.bg{{fill:{lb}}}.fg{{fill:{lf}}}.bd{{stroke:{lbd}}}.mut{{fill:{lm}}}"
                 f"@media(prefers-color-scheme:dark){{.bg{{fill:{db}}}.fg{{fill:{df}}}"
                 f".bd{{stroke:{dbd}}}.mut{{fill:{dm}}}}}</style>")

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:.0f}" height="20" '
        f'viewBox="0 0 {w:.1f} 20" role="img" aria-label="{aria}">'
        f'<title>{aria}</title>{style}'
        f'<rect x=".5" y=".5" width="{w-1:.1f}" height="19" rx="4" class="bg bd" '
        f'fill-opacity="1" stroke-width="1"/>'
        f'<g transform="translate({pad:.1f},4.7)">' + _MARK.replace("{fg}", "currentColor")
        .replace('fill="currentColor"', 'class="fg"') + '</g>'
        f'<text x="{lx:.1f}" y="13.6" class="fg" font-family="{_FONT}" font-size="11" '
        f'font-weight="560" letter-spacing=".1">{label}</text>'
        f'<line x1="{left_w-gap/2:.1f}" y1="4" x2="{left_w-gap/2:.1f}" y2="16" '
        f'class="bd" stroke-width="1"/>'
        f'<text x="{left_w:.1f}" y="13.6" class="mut" font-family="{_FONT}" font-size="11" '
        f'letter-spacing=".1">{value}</text>'
        f'</svg>')


def render(conn: sqlite3.Connection, publisher: str, theme: str = "auto") -> str:
    """The badge for one publisher.

    A publisher we do not hold gets a neutral badge rather than an error: the
    URL will be pasted into a README before we have crawled the domain, and a
    broken image where a badge should be reads as our failure, not theirs.
    """
    st = stats_for(conn, publisher)
    if st is None:
        return _svg("ARD Registry", "not indexed yet", theme)
    tools, servers, responding = st
    if tools > 0:
        return _svg("ARD Registry", f"{tools:,} tool" + ("s" if tools != 1 else "")
                    + (" verified" if responding else " indexed"), theme)
    if responding:
        return _svg("ARD Registry", "endpoint verified", theme)
    return _svg("ARD Registry", "indexed", theme)


def snippet(publisher: str, theme: str = "auto") -> dict:
    """Paste-ready embeds.

    The link goes to the publisher's own page on this index, not to the home
    page: it is a real page about them, so the badge sends their reader
    somewhere useful rather than to an advertisement.

    The `alt` text is not decoration. An image link carries no anchor text, so
    the alt attribute is the only description a machine reading the page gets.
    """
    B = config.PUBLIC_BASE
    q = "" if theme == "auto" else f"?theme={theme}"
    img = f"{B}/badge/{publisher}.svg{q}"
    href = f"{B}/ard-publishers/{publisher}"
    alt = f"{publisher} on the Neuronto ARD Registry"
    # An image link carries no anchor text, so a text variant is offered too: it
    # is the only form where the words describing the link are the link. Both are
    # plain links; nothing here adds `nofollow`, and `noopener` is a security
    # attribute that has no effect on how a link is followed or read.
    text_label = f"Verified on the Neuronto ARD Registry"
    return {
        "html": (f'<a href="{href}" target="_blank" rel="noopener">'
                 f'<img src="{img}" alt="{alt}" height="20"></a>'),
        "markdown": f"[![{alt}]({img})]({href})",
        "rst": f".. image:: {img}\n   :alt: {alt}\n   :target: {href}",
        "text_html": f'<a href="{href}" rel="noopener">{text_label}</a>',
        "text_markdown": f"[{text_label}]({href})",
        "image": img,
        "link": href,
        "alt": alt,
    }
